<?php

/*
AutoIndex.conf.php generated by config.php
Part of AutoIndex PHP Script
http://autoindex.sourceforge.net
*/



/*  Required settings:  */

$base_dir = './';
$icon_path = '/AutoIndex/index_icons/winxp';
$stylesheet = '/AutoIndex/stylesheet.css';


/*  Optional settings:  */

$use_login_system = false;
$allow_uploads = false;
$must_login_to_download = false;
$user_list = '.htpasswd.autoindex';
$allow_file_overwrites = false;
$log_file = '';
$dont_log_these_ips = array(
	"127.0.0.*",
);
$banned_list = '';
$download_count = '';
$links_file = '';
$description_file = '';
$sub_folder_access = true;
$index = '';
$hidden_files = array(
	"$log_file",
	"$links_file",
	"$description_file",
	"$banned_list",
	"$stylesheet",
	"$download_count",
	"index_icons",
	"languages",
	"*.php",
	".ht*",
	"*~",
	".*",
);
$show_only_these_files = array();
$force_download = true;
$bandwidth_limit = 0;
$anti_leech = false;
$enable_searching = true;
$show_dir_size = true;
$folder_expansion = true;
$show_folder_count = true;
$days_new = 0;
$md5_show = 0;
$thumbnail_height = 0;
$header = '';
$footer = '';
$header_per_folder = false;
$footer_per_folder = false;
$show_type_column = false;
$show_size_column = true;
$show_date_column = true;
$path_to_language_files = '/usr/share/AutoIndex/languages/';
$lang = 'en';
$select_language = false;

?>
